//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarsApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journey
    {
        public int journey_id { get; set; }
        public string journey1 { get; set; }
        public int departure { get; set; }
        public int destination { get; set; }
        public int car_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> distance { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Point Point { get; set; }
        public virtual Point Point1 { get; set; }
    }
}
